Add disclaimer
GCPAoR/cpaor-data-viz-dashboard pull request #4
Opened 2024-12-20 09:45 UTC by ranjan-stha

* Add the disclaimer
* Handle the local storage for caching a piece of data
* Update the streamlit version.

2024-12-20 11:43 UTC, AdityaKhatri requested changes

2024-12-20 11:43 UTC, AdityaKhatri commented on frontend_src/app.py
> +cached_disclaimer_data = local_storage.getItem("cpaor_data")
```suggestion
cached_disclaimer_data = local_storage.getItem("cpaor_consent_confirm")
```

2024-12-20 11:43 UTC, AdityaKhatri commented on frontend_src/app.py
> +    local_storage.setItem("cpaor_data", "disclaimer_displayed")
```suggestion
    local_storage.setItem("cpaor_consent_confirm", "false")
```

2024-12-25 06:16 UTC, ranjan-stha commented on frontend_src/app.py
> +cached_disclaimer_data = local_storage.getItem("cpaor_data")
done

2024-12-25 06:17 UTC, ranjan-stha commented on frontend_src/app.py
> +    local_storage.setItem("cpaor_data", "disclaimer_displayed")
done

2024-12-26 04:56 UTC, AdityaKhatri approved these changes

2024-12-26 04:56 UTC, merged